# model configs

# model name (hint: check ../config/models.yaml) (default: large_gnm)
model: 'gnm_large'
# temporal distance within the next node in the topomap before localizing to it (default: 3)
close_threshold: 3
# temporal number of locobal nodes to look at in the topopmap for localization (default: 2)
radius: 2
# index of the waypoint used for navigation (between 0 and 4 or how many waypoints your model predicts) (default: 2)
waypoint: 2
# goal node index in the topomap (if -1, then the goal node is the last node in the topomap) (default: -1)
goal_node: -1
# mode: policy, video, or manual
mode: 'policy'
# path to topomap images
dir: 'testing'

# configs for camera.
resolution: 256
width: 256
height: 256

sensor_position:
  - 0
  - 1.25
  - 0
sensor_orientation: 
  - 0
  - 0
  - 0 
hfov: 90

# configs for loadind scenes dataset
scenes_dir: '../../data/habitat/scene_datasets'
data_path: '../../data/habitat/datasets/pointnav/habitat-test-scenes/v1/train/train.json.gz'

# log results.
logdir: &reference_dir '../configs_output/habitat/gnm/${now:%m-%d}/${now:%H-%M}'

# Disable logging
defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

hydra:
  output_subdir: null
  run:
    dir: .