# training configs
learning_rate: 0.001
epochs: 80

# Load data configs
preprocessed_features: true
preprocessed_dataset: true
batch_size: 512
interval: 3
dataset_dir: '/data/yuquand/a1_demo/'

# device.
no_gpu: false
which_gpu: 0

# log results.
save_params: false
save_log: false
logdir: &reference_dir '../configs_output/siamese/${now:%m-%d}/${now:%H-%M}'

# Default: No auto-logging.  
defaults:  
- _self_  
- override hydra/hydra_logging: disabled  
- override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .